name: Flusso SINGOLO Spese-Entrate 

on:
  workflow_dispatch:
    inputs:
      anno:
        description: "Anno"
        default: "2026"
        required: true
        type: string
      mese:
        description: "Mese"
        required: true
        type: choice
        options:
          - Gennaio
          - Febbraio
          - Marzo
          - Aprile
          - Maggio
          - Giugno
          - Luglio
          - Agosto
          - Settembre
          - Ottobre
          - Novembre
          - Dicembre
      flag_prioritizza_prc:
        description: "Salto elaborazione"
        required: true
        default: false
        type: boolean
      flag_scrittura_sul_drive:
        description: "Se disattivato non scrive sullo Sheet"
        required: false
        default: true
        type: boolean
      flag_sovrascrivo_sheet:
        description: "Se disattivato il flusso si blocca se lo sheet non è vuoto"
        required: false
        default: true
        type: boolean
      log_duplicati:
        description: "Stampa i record duplici"
        required: false
        default: false
        type: boolean
      log_altro:
        description: "Stampa i Categoria = 'Altro'"
        required: false
        default: false
        type: boolean
      flag_tutti_raw:
        description: "Esegue il codice su tutti i file raw presenti sul DropBox"
        required: false
        default: false
        type: boolean

jobs:
  flusso:
    runs-on: ubuntu-latest

    env:
      FLAG_AUTOMATIC: false
      FLAG_TUTTI_RAW:               ${{ inputs.flag_tutti_raw }}
      FLAG_SCRITTURA_SUL_DRIVE:     ${{ inputs.flag_scrittura_sul_drive }}
      FLAG_SOVRASCRIVO_SHEET:       ${{ inputs.flag_sovrascrivo_sheet }}
      FLAG_LOG_DUPLICATI:           ${{ inputs.log_duplicati }}
      FLAG_LOG_ALTRO:               ${{ inputs.log_altro }}
      ANNO: ${{ inputs.anno }}
      MESE: ${{ inputs.mese }}
      DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
      DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
      DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installa dipendenze
        run: pip install -r requirements.txt

      - name: Esegui flusso
        run: python main_job_single.py