name: Flusso Spese

on:
  workflow_dispatch:
    inputs:
      automatico:
          description: "1 se determina automaticamente i file da processare"
          required: true
          type: boolean
      anno:
        description: "Anno (es. 2026)"
        required: false
        type: string
      mese:
        description: "Mese (es. 06)"
        required: false
        type: string

jobs:
  flusso:
    runs-on: ubuntu-latest

    env:
      FLAG_AUTO_ANNO_MESE: ${{ inputs.automatico }}
      ANNO: ${{ inputs.anno }}
      MESE: ${{ inputs.mese }}
      DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
      DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
      DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installa dipendenze
        run: pip install -r requirements.txt

      - name: Esegui flusso
        run: python FLUSSO_TOTALE.py