name: Flusso Spese

on:
  workflow_dispatch:
    inputs:
      automatico:
          description: "Autodetection dei file da elaborare"
          required: true
          type: boolean
      log_duplicati:
          description: "Stampa i record duplici"
          required: true
          default: false
          type: boolean
      log_altro:
          description: "Stampa i record che hanno Categoria = 'Altro'"
          required: true
          default: false
          type: boolean
      anno:
        description: "Anno (es. 2026)"
        required: false
        default: "2026"
        type: string
      mese:
        description: "Mese (es. 06)"
        required: false
        type: choice
        options:
          - '01'
          - '02'
          - '03'
          - '04'
          - '05'
          - '06'
          - '07'
          - '08'
          - '09'
          - '10'
          - '11'
          - '12'

jobs:
  flusso:
    runs-on: ubuntu-latest

    env:
      FLAG_LOG_DUPLICATI:   ${{ inputs.log_duplicati }}
      FLAG_LOG_ALTRO:       ${{ inputs.log_altro }}
      FLAG_AUTO_ANNO_MESE:  ${{ inputs.automatico }}
      ANNO: ${{ inputs.anno }}
      MESE: ${{ inputs.mese }}
      DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
      DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
      DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installa dipendenze
        run: pip install -r requirements.txt

      - name: Esegui flusso
        run: python FLUSSO_TOTALE.py